### PR TITLE
Minor formatting

### PR DESCRIPTION
**Pull request by pllim**
PR to your PR as requested. Thanks!

### CODE REVIEW

**Comment by sosey** [comment]
The updates dont render properly: 
screen shot 2018-10-25 at 1 27 21 pm

**Comment by pllim** [comment]
Yeah. Weird.

**Comment by pllim** [comment]
OK I think I fixed it.

**Comment by sosey** [comment]
almost, but not quite:
screen shot 2018-10-25 at 1 35 32 pm

**Comment by pllim** [comment]
All the other sentences also use single quotes. At least I am being consistent?

**Comment by pllim** [comment]
TBH GitHub plays nicer with markdown, so might as well change this from RST to MD... :speak_no_evil:

**Comment by sosey** [comment]
yah, I know, I had the same issue, which is why I had it the other way ;) Also, markdown sometimes makes me want to  (┛ಠ_ಠ)┛彡┻━┻

**Comment by sosey** [comment]
I'm fine with switching this to md, update if you like

**Comment by pllim** [comment]
I removed the quotes. Naw, it is okay for now. Switching to MD is out of scope and I have a bunch of other stuff to catch up on. That's what I get for going on vacation. :(

**Comment by sosey** [comment]
The formatting is still off a bit here, I'm gunna go ahead and close this, and just use the original PR, with an update to md.

**Pull request closed without merging**
